- name: Ansible Data Types
  hosts: web

  vars:
    # 1️-String Data Type
    course: "DevOps with AWS"

    # 2️-Integer Data Type
    id: 3251

    # 3️-Boolean Data Type (True or False)
    live: true

    # 4️-List Data Type (Array)
    topics:
      - AWS
      - Linux
      - "Shell Scripting"  
      - Ansible
      - Terraform
      - Docker
      - Kubernetes
      - Git
      - Monitoring

    # 5️-Dictionary Data Type (Key-Value Pairs)
    details:
      course: "DevOps with AWS"
      duration: 120
      location: "Online"

    # 6️-Null (None) Data Type
    fees: null

  tasks:
    - name: Display String
      ansible.builtin.debug:
        msg: "Hello We are Teaching {{ course }}"

    - name: Display Integer
      ansible.builtin.debug:
        msg: "Course ID is - {{ id }}"

    - name: Display Boolean
      ansible.builtin.debug:
        msg: " is it live? - {{ live }}"

    - name: Display List
      ansible.builtin.debug:
        msg: "DevOps Topics We Will Cover {{ topics }}"

    - name: Display Dictionary
      ansible.builtin.debug:
        msg: "Course Details are: Course={{ details.course }}, Duration={{ details.duration }}, Location={{ details.location }}"

    - name: Display Null Value
      ansible.builtin.debug:
        msg: "Entry Fees: {{ fees }}"