- name: Check value is greater than 51 or not
  hosts: local
  connection: local
  vars:
    my_number: 59
  tasks:
  - name: Print if number greater than 51
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is greater than 51"
    when: my_number > 51

  - name: Print if number less than or equal to 51
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is less than or equal to 51"
    when: my_number <= 51
