- name: Ansible Loops All Examples
  hosts: web
  gather_facts: false

  vars:
    fruits:
      - apple
      - banana
      - mango

    user_info:
      alice: "developer"
      bob: "admin"

    servers:
      - web
      - db

    ports:
      - 80
      - 443

    files_to_read:
      - "/etc/hosts"
      - "/etc/passwd"

  tasks:

    # 1-with_items — Basic loop
    - name: Print list of fruits (with_items)
      debug:
        msg: "Fruit: {{ item }}"
      with_items: "{{ fruits }}"

    # 2-loop — Modern way (same as with_items)
    - name: Print list of fruits (loop)
      debug:
        msg: "Fruit (loop): {{ item }}"
      loop: "{{ fruits }}"

    # 3-with_dict — Loop over key-value pairs
    - name: Show user roles
      debug:
        msg: "User {{ item.key }} is a {{ item.value }}"
      with_dict: "{{ user_info }}"

    # 4-with_indexed_items — Get index with loop
    - name: Show index and item
      debug:
        msg: "Index {{ item.0 }}: Fruit = {{ item.1 }}"
      with_indexed_items: "{{ fruits }}"

    # 5-with_nested — Nested loops (like 2D)
    - name: Combine servers and ports
      debug:
        msg: "Server: {{ item.0 }}, Port: {{ item.1 }}"
      with_nested:
        - "{{ servers }}"
        - "{{ ports }}"

    # 6-with_file — Loop through local files (must exist)
    - name: Show file content (if files exist)
      shell: cat {{ item }}
      register: file_output
      ignore_errors: yes
      with_file: "{{ files_to_read }}"

    - name: Show file read results
      debug:
        var: file_output.results

