- name: Store Output Example
  hosts: local
  connection: local
  tasks:

    # 1️-Register the output of a shell command
    - name: Get system uptime
      ansible.builtin.command: uptime
      register: uptime_output

    - name: Display uptime output
      ansible.builtin.debug:
        msg: "System Uptime: {{ uptime_output.stdout }}"

    # 2-Register the output of a package check
    - name: Check if Nginx is installed
      ansible.builtin.command: "rpm -qa | grep nginx"
      register: nginx_status
      ignore_errors: yes  # Avoid failure if Nginx is not installed

    - name: Install Nginx if not found
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: nginx_status.rc != 0  # Runs only if Nginx is not installed